package id.homebase.core.image

import id.homebase.api.client.drives.files.ThumbnailDescriptor
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Unit tests for the thumbnail size-selection helpers that back the
 * native-sized thumbnail request (so the optimistic seed is served and the
 * disk cache no longer mints an entry per measured size). See [selectThumbSize]
 * and [thumbSizesFrom].
 */
class ThumbSizeSelectionTest {

    // Native sizes generated by the sender (aspect-correct, landscape 4:3),
    // mirroring ThumbnailGenerator's 320/640/1080 instructions.
    private val landscapeNatives = listOf(
        ImageSize(320, 240),
        ImageSize(640, 480),
        ImageSize(1080, 810),
    )

    @Test
    fun `empty available returns the requested size unchanged`() {
        // Link previews / avatars have no descriptor — keep requesting whatever
        // the layout measured, exactly as before.
        val requested = ImageSize(712, 950)
        assertEquals(requested, selectThumbSize(requested, emptyList()))
    }

    @Test
    fun `request smaller than all natives picks the smallest native`() {
        assertEquals(ImageSize(320, 240), selectThumbSize(ImageSize(70, 90), landscapeNatives))
    }

    @Test
    fun `request between two natives picks the smallest native that covers it`() {
        // longest edge 500 -> smallest native whose longest edge >= 500 is 640.
        assertEquals(ImageSize(640, 480), selectThumbSize(ImageSize(500, 400), landscapeNatives))
    }

    @Test
    fun `request equal to a native picks that native`() {
        assertEquals(ImageSize(640, 480), selectThumbSize(ImageSize(640, 480), landscapeNatives))
    }

    @Test
    fun `request larger than all natives clamps to the largest native`() {
        // The server has nothing bigger than 1080 — clamp instead of upscaling.
        assertEquals(ImageSize(1080, 810), selectThumbSize(ImageSize(2000, 2000), landscapeNatives))
    }

    @Test
    fun `selection compares on the longest edge for portrait requests`() {
        // Portrait request 240x320 -> longest edge 320 -> smallest native (320).
        assertEquals(ImageSize(320, 240), selectThumbSize(ImageSize(240, 320), landscapeNatives))
        // Portrait request 240x500 -> longest edge 500 -> 640.
        assertEquals(ImageSize(640, 480), selectThumbSize(ImageSize(240, 500), landscapeNatives))
    }

    @Test
    fun `single native is always selected`() {
        val only = listOf(ImageSize(320, 240))
        assertEquals(ImageSize(320, 240), selectThumbSize(ImageSize(70, 90), only))
        assertEquals(ImageSize(320, 240), selectThumbSize(ImageSize(9000, 9000), only))
    }

    @Test
    fun `thumbSizesFrom maps descriptors and drops invalid dimensions`() {
        val descriptors = listOf(
            ThumbnailDescriptor(pixelWidth = 320, pixelHeight = 240, contentType = "image/webp"),
            ThumbnailDescriptor(pixelWidth = 640, pixelHeight = 480, contentType = "image/webp"),
            ThumbnailDescriptor(pixelWidth = null, pixelHeight = 480),  // missing width -> dropped
            ThumbnailDescriptor(pixelWidth = 100, pixelHeight = null),  // missing height -> dropped
            ThumbnailDescriptor(pixelWidth = 0, pixelHeight = 0),       // non-positive -> dropped
        )
        assertEquals(
            listOf(ImageSize(320, 240), ImageSize(640, 480)),
            thumbSizesFrom(descriptors)
        )
    }

    @Test
    fun `thumbSizesFrom returns empty for null or empty input`() {
        assertTrue(thumbSizesFrom(null).isEmpty())
        assertTrue(thumbSizesFrom(emptyList()).isEmpty())
    }
}
