include required("conveyor_common.conf")

app {
  site {
    base-url = "https://github.com/homebase-id/soundhouse-desktop-release-bleeding/releases/latest/download"
    github.oauth-token = ${env.CONVEYOR_GITHUB_TOKEN}
  }

  display-name = "Soundhouse Dev"
  vendor = "Homebase"
  contact-email = "apps@vidence.co"
  rdns-name = "id.homebase.audio.dev"

  // For iteration speed; the production config keeps the default.
  compression-level = low

  jvm {
    system-properties {
      "app.rdns.name" = "id.homebase.audio.dev"
    }
  }
}
