include required("conveyor_common.conf")

app {
  site {
    base-url = "https://github.com/homebase-id/soundhouse-desktop-release-production/releases/latest/download"
    github.oauth-token = ${env.CONVEYOR_GITHUB_TOKEN}
  }

  display-name = "Soundhouse"
  vendor = "Homebase"
  contact-email = "apps@vidence.co"
  rdns-name = "id.homebase.audio"

  jvm {
    system-properties {
      "app.rdns.name" = "id.homebase.audio"
    }
  }

  windows {
    signing-key {
      azure-trusted-signing {
        endpoint = "eus.codesigning.azure.net"
        api-access-token = ${env.AZURE_ACCESS_TOKEN}
      }
    }
    signing-key-alias = "HomebaseId/homebase-id-app-public-cert-profile"
  }

  mac {
    certificate = ${env.APPLE_P12_PATH}

    signing-key.file = {
      path = ${env.APPLE_P12_PATH}
      password = ${env.APPLE_SIGNING_KEY_PASS}
    }

    notarization {
      issuer-id = ${env.APPSTORE_API_ISSUER_ID}
      key-id = ${env.APPSTORE_API_KEY_ID}
      private-key = ${env.APPLE_NOTARIZATION_KEY}
    }
  }
}
