package id.homebase.api.sync.database

import id.homebase.api.client.drives.HomebaseFile
import id.homebase.api.serialization.OdinSystemSerializer
import id.homebase.api.client.drives.query.QueryBatchCursor
import kotlin.uuid.Uuid

/**
 * Helper functions for DriveMainIndex operations
 */
object MainIndexMetaHelpers {
    /**
     * Helper upsert function that takes a DriveMainIndex record and calls
     * database.upsertDriveMainIndex() with all the members.
     */
    suspend fun upsertDriveMainIndex(
        databaseManager: DatabaseManager,
        driveMainIndexRecord: DriveMainIndex
    ) {
        databaseManager.driveMainIndex.upsertDriveMainIndex(
            identityId = driveMainIndexRecord.identityId,
            driveId = driveMainIndexRecord.driveId,
            fileId = driveMainIndexRecord.fileId,
            globalTransitId = driveMainIndexRecord.globalTransitId,
            uniqueId = driveMainIndexRecord.uniqueId,
            groupId = driveMainIndexRecord.groupId,
            senderId = driveMainIndexRecord.senderId,
            originalAuthor = driveMainIndexRecord.originalAuthor,
            fileType = driveMainIndexRecord.fileType,
            dataType = driveMainIndexRecord.dataType,
            archivalStatus = driveMainIndexRecord.archivalStatus,
            fileState = driveMainIndexRecord.fileState,
            historyStatus = driveMainIndexRecord.historyStatus,
            userDate = driveMainIndexRecord.userDate,
            created = driveMainIndexRecord.created,
            modified = driveMainIndexRecord.modified,
            fileSystemType = driveMainIndexRecord.fileSystemType,
            jsonHeader = driveMainIndexRecord.jsonHeader,
        )
    }

    fun upsertDriveMainIndex(
        db: OdinDatabase,
        driveMainIndexRecord: DriveMainIndex
    ): Long {
        return db.driveMainIndexQueries.upsertDriveMainIndex(
            identityId = driveMainIndexRecord.identityId,
            driveId = driveMainIndexRecord.driveId,
            fileId = driveMainIndexRecord.fileId,
            globalTransitId = driveMainIndexRecord.globalTransitId,
            uniqueId = driveMainIndexRecord.uniqueId,
            groupId = driveMainIndexRecord.groupId,
            senderId = driveMainIndexRecord.senderId,
            originalAuthor = driveMainIndexRecord.originalAuthor,
            fileType = driveMainIndexRecord.fileType,
            dataType = driveMainIndexRecord.dataType,
            archivalStatus = driveMainIndexRecord.archivalStatus,
            fileState = driveMainIndexRecord.fileState,
            historyStatus = driveMainIndexRecord.historyStatus,
            userDate = driveMainIndexRecord.userDate,
            created = driveMainIndexRecord.created,
            modified = driveMainIndexRecord.modified,
            fileSystemType = driveMainIndexRecord.fileSystemType,
            jsonHeader = driveMainIndexRecord.jsonHeader,
        ).value
    }

    /**
     * Processes file metadata with associated tags from different index tables.
     * Takes a DriveMainIndex record and lists of DriveTagIndex and DriveLocalTagIndex records.
     */
    class HomebaseFileProcessor(
        private val databaseManager: DatabaseManager
    ) {
        suspend fun deleteEntryDriveMainIndex(
            identityId: Uuid,
            driveId: Uuid,
            fileId: Uuid
        ) {
            databaseManager.withWriteTransaction { db ->
                db.driveMainIndexQueries.deleteBy(identityId, driveId, fileId)
                db.driveTagIndexQueries.deleteByFile(identityId, driveId, fileId)
                db.driveLocalTagIndexQueries.deleteByFile(identityId, driveId, fileId)
            }
        }

        /**
         * Converts SharedSecretEncryptedFileHeader to ParsedHeaderResult
         *
         * @param identityId Identity ID (required, not in header)
         * @param driveId Drive ID (required, not in header)
         * @param header SharedSecretEncryptedFileHeader containing file metadata
         * @return ParsedHeaderResult containing DriveMainIndex and tag records
         */
        fun convertFileHeaderToDriveMainIndexRecord(
            identityId: Uuid,
            driveId: Uuid,
            header: HomebaseFile
        ): DriveMainIndex {
            // Serialize header back to JSON for storage
            val jsonHeader = OdinSystemSerializer.serialize(header)

            val driveMainIndex = DriveMainIndex(
                rowId = 0L, // Will be auto-generated by database
                identityId = identityId,
                driveId = driveId,
                fileId = header.fileId,
                uniqueId = header.fileMetadata.appData.uniqueId,
                globalTransitId = header.fileMetadata.globalTransitId,
                senderId = header.fileMetadata.senderOdinId?.domainName,
                originalAuthor = header.fileMetadata.originalAuthor?.domainName,
                groupId = header.fileMetadata.appData.groupId,
                fileType = (header.fileMetadata.appData.fileType ?: 0).toLong(),
                dataType = (header.fileMetadata.appData.dataType ?: 0).toLong(),
                archivalStatus = (header.fileMetadata.appData.archivalStatus?.value ?: 0).toLong(),
                fileState = header.fileState.value.toLong(),
                historyStatus = 0L,
                // Fall back to `metadata.created` when appData.userDate is null —
                // older Web/RN clients didn't always capture userDate, and the
                // in-memory MessageUiModel mapper falls back to a server-stamped
                // timestamp too (see ChatMessageStream.mapToMessageData). Storing
                // 0 here would put those rows at the epoch, which makes any SQL
                // filter on userDate (notably the unread-count queries) disagree
                // with the in-memory list ordering. `created` is always set on
                // real rows and is the same fallback the soft-delete branch in
                // mapToMessageData uses, so we land on the same wall-clock time.
                userDate = header.fileMetadata.appData.userDate
                    ?: header.fileMetadata.created.milliseconds,
                created = header.fileMetadata.created.milliseconds,
                modified = header.fileMetadata.updated.milliseconds,
                fileSystemType = 0L, // Default value
                jsonHeader = jsonHeader
            )

            return driveMainIndex
        }

        /**
         * Converts DriveMainIndex.jsonHeader back to SharedSecretEncryptedFileHeader
         * This is the inverse function of convertFileHeaderToDriveMainIndexRecord
         *
         * @param driveMainIndex DriveMainIndex record containing the jsonHeader
         * @return SharedSecretEncryptedFileHeader reconstructed from the stored JSON
         * @throws Exception if JSON deserialization fails
         */
        fun convertDriveMainIndexRecordToFileHeader(
            driveMainIndex: DriveMainIndex
        ): HomebaseFile {
            try {
                return OdinSystemSerializer.deserialize<HomebaseFile>(driveMainIndex.jsonHeader)
            } catch (e: Exception) {
                throw IllegalStateException("Corrupt DB row: fileId=${driveMainIndex.fileId}, json=${driveMainIndex.jsonHeader.take(200)}", e)
            }
        }

        /**
         * Upserts multiple file entries into the database using the provided SharedSecretEncryptedFileHeaders
         * All operations are performed within a single thread-safe database transaction for atomicity.
         * otherwise uses direct database transaction (for tests).
         *
         * @param identityId Identity ID (required, not in header)
         * @param driveId Drive ID (required, not in header)
         * @param fileHeaders List of SharedSecretEncryptedFileHeader containing file metadata
         * @param cursor Optional current cursor to be saved
         */
        suspend fun baseUpsertEntryZapZap(
            identityId: Uuid,
            driveId: Uuid,
            fileHeaders: List<HomebaseFile>,
            cursor: QueryBatchCursor?
        ): List<HomebaseFile> {
            return performBaseUpsert(identityId, driveId, fileHeaders, cursor)
        }

        /**
         * Internal helper method that performs the actual upsert operations.
         * Separated to avoid code duplication between transaction strategies.
         * Made public for testing thread safety within transactions.
         */
        suspend fun performBaseUpsert(
            identityId: Uuid,
            driveId: Uuid,
            fileHeaders: List<HomebaseFile>,
            cursor: QueryBatchCursor?
        ): List<HomebaseFile> {
            // The headers that actually changed a row (passed the DriveMainIndex
            // timestamp guard, n > 0). Callers — notably DriveWebSocketUpsertWorker
            // — emit BatchReceived from THIS list, not the raw incoming batch, so a
            // stale/duplicate server push the guard rejected never reaches the UI.
            val written = ArrayList<HomebaseFile>(fileHeaders.size)
            databaseManager.withWriteTransaction { db ->

                fileHeaders.forEach { fileHeader ->
                    // Convert SharedSecretEncryptedFileHeader to extract DriveMainIndex fields and tag records
                    val driveMainIndexRecord =
                        convertFileHeaderToDriveMainIndexRecord(identityId, driveId, fileHeader)

                    var n = upsertDriveMainIndex(db, driveMainIndexRecord)

                    // if n < 1 then the record wasn't written (because its modified timestamp was
                    // less or equal to the existing modified timestamp), we only want to update the
                    // TAGs if the record is "new"
                    if (n <= 0L) {
                        adoptServerOwnedFields(db, identityId, driveId, fileHeader, driveMainIndexRecord)
                            ?.let { written.add(it) }
                    }
                    if (n > 0L) {
                        written.add(fileHeader)
                        rewriteTags(db, identityId, driveId, fileHeader)
                    }

                    // Even if we didn't update the record we advance the cursor
                    if (cursor != null) {
                        val cursorStorage = CursorStorage(databaseManager, driveId)
                        cursorStorage.saveCursor(db, cursor)
                    }
                }
            }
            return written
        }

        private fun rewriteTags(db: OdinDatabase, identityId: Uuid, driveId: Uuid, fileHeader: HomebaseFile) {
            db.driveTagIndexQueries.deleteByFile(
                identityId = identityId,
                driveId = driveId,
                fileId = fileHeader.fileId
            )
            db.driveLocalTagIndexQueries.deleteByFile(
                identityId = identityId,
                driveId = driveId,
                fileId = fileHeader.fileId
            )

            var n = 0L
            var l = 0L
            fileHeader.fileMetadata.appData.tags?.forEach { tagRecord ->
                n += db.driveTagIndexQueries.insertTag(
                    identityId = identityId,
                    driveId = driveId,
                    fileId = fileHeader.fileId,
                    tagId = tagRecord
                ).value
                l++
            }
            if (n != l)
                throw IllegalStateException("Unable to write TAGs")

            n = 0L
            l = 0L
            fileHeader.fileMetadata.localAppData?.tags?.forEach { tagRecord ->
                n += db.driveLocalTagIndexQueries.insertLocalTag(
                    identityId = identityId,
                    driveId = driveId,
                    fileId = fileHeader.fileId,
                    tagId = tagRecord
                ).value
                l++
            }

            if (n != l)
                throw IllegalStateException("Unable to write local TAGs")
        }

        // transferHistory/originalRecipientCount are server-owned: on an equal-`modified` rejection adopt only those into the stored row. Runs inside the caller's write transaction.
        private fun adoptServerOwnedFields(
            db: OdinDatabase,
            identityId: Uuid,
            driveId: Uuid,
            incoming: HomebaseFile,
            incomingRecord: DriveMainIndex,
        ): HomebaseFile? {
            val history = incoming.serverMetadata.transferHistory ?: return null
            val uniqueId = incomingRecord.uniqueId
            val stored = (
                if (uniqueId != null) {
                    db.driveMainIndexQueries.selectByIdentityAndDriveAndUnique(identityId, driveId, uniqueId)
                } else {
                    db.driveMainIndexQueries.selectByIdentityAndDriveAndFile(identityId, driveId, incomingRecord.fileId)
                }
                ).executeAsOneOrNull() ?: return null
            if (incomingRecord.modified < stored.modified) return null

            val storedFile = OdinSystemSerializer.deserialize<HomebaseFile>(stored.jsonHeader)
            val storedMeta = storedFile.serverMetadata
            val recipientCount =
                if (storedMeta.originalRecipientCount == 0) incoming.serverMetadata.originalRecipientCount
                else storedMeta.originalRecipientCount
            if (storedMeta.transferHistory == history && storedMeta.originalRecipientCount == recipientCount) return null

            val merged = storedFile.copy(
                serverMetadata = storedMeta.copy(transferHistory = history, originalRecipientCount = recipientCount)
            )
            db.driveMainIndexQueries.repairJsonHeaderByRowId(OdinSystemSerializer.serialize(merged), stored.rowId)
            return merged
        }

        /**
         * Upserts a single file entry into the database using the provided SharedSecretEncryptedFileHeader
         * This is a backwards-compatible helper that calls the batch version with a single-item list.
         *
         * @param identityId Identity ID (required, not in header)
         * @param driveId Drive ID (required, not in header)
         * @param fileHeader SharedSecretEncryptedFileHeader containing file metadata
         * @param cursor Optional current cursor to be saved
         */
        suspend fun baseUpsertEntryZapZap(
            identityId: Uuid,
            driveId: Uuid,
            fileHeader: HomebaseFile,
            cursor: QueryBatchCursor?
        ): List<HomebaseFile> {
            return baseUpsertEntryZapZap(identityId, driveId, listOf(fileHeader), cursor)
        }
    }
}
