version.name=1.4.1505
version.code.base=1505

# In Github actions we will generate version.name like MAJOR.MINOR.[version.code.base + BUILD_NUMBER]
#
# So for example if these are the values in version.properties:
# Version name is 1.3.1200
# Version code base is 1200
#
# And the Github action build number is 7
#
# This will result in version name that is 1.3.1207
